version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: painter_booking_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: painter_booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - painter_booking_network

  # NestJS Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: painter_booking_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: painter_booking_db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - painter_booking_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: painter_booking_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - painter_booking_network

volumes:
  postgres_data:

networks:
  painter_booking_network:
    driver: bridge
